spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/apcdb
      database: apcdb
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: https://accounts.google.com

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
