spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/apcdb
      database: apcdb

server:
  port: 8000

spring.main.allow-bean-definition-overriding=true:

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
